/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int BREAK = 9;
  int BYTE = 10;
  int CASE = 11;
  int CATCH = 12;
  int CHAR = 13;
  int CLASS = 14;
  int CONST = 15;
  int CONTINUE = 16;
  int DEFAULT_ = 17;
  int DO = 18;
  int DOUBLE = 19;
  int ELSE = 20;
  int EXTENDS = 21;
  int FALSE = 22;
  int FINAL = 23;
  int FINALLY = 24;
  int FLOAT = 25;
  int FOR = 26;
  int GOTO = 27;
  int IF = 28;
  int IMPLEMENTS = 29;
  int IMPORT = 30;
  int INSTANCEOF = 31;
  int INT = 32;
  int INTERFACE = 33;
  int LONG = 34;
  int NATIVE = 35;
  int NEW = 36;
  int NULL = 37;
  int PACKAGE = 38;
  int PRIVATE = 39;
  int PROTECTED = 40;
  int PUBLIC = 41;
  int RETURN = 42;
  int SHORT = 43;
  int STATIC = 44;
  int STRICTFP = 45;
  int SUPER = 46;
  int SWITCH = 47;
  int SYNCHRONIZED = 48;
  int THIS = 49;
  int THROW = 50;
  int THROWS = 51;
  int TRANSIENT = 52;
  int TRUE = 53;
  int TRY = 54;
  int VOID = 55;
  int VOLATILE = 56;
  int WHILE = 57;
  int PLUS = 58;
  int ASSIGN = 59;
  int DEC = 60;
  int EQUAL = 61;
  int GT = 62;
  int INC = 63;
  int LAND = 64;
  int LE = 65;
  int LNOT = 66;
  int MINUS = 67;
  int STAR = 68;
  int PLUS_ASSIGN = 69;
  int MINUS_ASSIGN = 70;
  int MULT_ASSIGN = 71;
  int DIV_ASSIGN = 72;
  int REM_ASSIGN = 73;
  int AND_ASSIGN = 74;
  int OR_ASSIGN = 75;
  int XOR_ASSIGN = 76;
  int USHR_ASSIGN = 77;
  int SHR_ASSIGN = 78;
  int SHL_ASSIGN = 79;
  int LPAREN = 80;
  int RPAREN = 81;
  int LCURLY = 82;
  int RCURLY = 83;
  int LBRACK = 84;
  int RBRACK = 85;
  int COLON = 86;
  int SEMI = 87;
  int COMMA = 88;
  int DOT = 89;
  int IDENTIFIER = 90;
  int LETTER = 91;
  int DIGIT = 92;
  int NON_ZERO_DIGIT = 93;
  int INT_LITERAL = 94;
  int DOUBLE_LITERAL = 95;
  int CHAR_LITERAL = 96;
  int STRING_LITERAL = 97;
  int ESC = 98;
  int ERROR = 99;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"*\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\">>>=\"",
    "\">>=\"",
    "\"<<=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
